#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_v1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CinemaDatabase")]
	public partial class DbCinemaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHall(Hall instance);
    partial void UpdateHall(Hall instance);
    partial void DeleteHall(Hall instance);
    partial void InsertReservation(Reservation instance);
    partial void UpdateReservation(Reservation instance);
    partial void DeleteReservation(Reservation instance);
    partial void InsertMovie(Movie instance);
    partial void UpdateMovie(Movie instance);
    partial void DeleteMovie(Movie instance);
    #endregion
		
		public DbCinemaDataContext() : 
				base(global::Cinema_v1.Properties.Settings.Default.CinemaDatabaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbCinemaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbCinemaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbCinemaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbCinemaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Hall> Halls
		{
			get
			{
				return this.GetTable<Hall>();
			}
		}
		
		public System.Data.Linq.Table<Reservation> Reservations
		{
			get
			{
				return this.GetTable<Reservation>();
			}
		}
		
		public System.Data.Linq.Table<Movie> Movies
		{
			get
			{
				return this.GetTable<Movie>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hall")]
	public partial class Hall : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _hId;
		
		private int _hAmountSeats;
		
		private EntityRef<Reservation> _Reservation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnhIdChanging(int value);
    partial void OnhIdChanged();
    partial void OnhAmountSeatsChanging(int value);
    partial void OnhAmountSeatsChanged();
    #endregion
		
		public Hall()
		{
			this._Reservation = default(EntityRef<Reservation>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int hId
		{
			get
			{
				return this._hId;
			}
			set
			{
				if ((this._hId != value))
				{
					if (this._Reservation.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnhIdChanging(value);
					this.SendPropertyChanging();
					this._hId = value;
					this.SendPropertyChanged("hId");
					this.OnhIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hAmountSeats", DbType="Int NOT NULL")]
		public int hAmountSeats
		{
			get
			{
				return this._hAmountSeats;
			}
			set
			{
				if ((this._hAmountSeats != value))
				{
					this.OnhAmountSeatsChanging(value);
					this.SendPropertyChanging();
					this._hAmountSeats = value;
					this.SendPropertyChanged("hAmountSeats");
					this.OnhAmountSeatsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Reservation_Hall", Storage="_Reservation", ThisKey="hId", OtherKey="hId", IsForeignKey=true)]
		public Reservation Reservation
		{
			get
			{
				return this._Reservation.Entity;
			}
			set
			{
				Reservation previousValue = this._Reservation.Entity;
				if (((previousValue != value) 
							|| (this._Reservation.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Reservation.Entity = null;
						previousValue.Halls.Remove(this);
					}
					this._Reservation.Entity = value;
					if ((value != null))
					{
						value.Halls.Add(this);
						this._hId = value.hId;
					}
					else
					{
						this._hId = default(int);
					}
					this.SendPropertyChanged("Reservation");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Reservation")]
	public partial class Reservation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _rId;
		
		private int _rSeat;
		
		private int _mId;
		
		private int _hId;
		
		private EntitySet<Movie> _Movies;
		
		private EntitySet<Hall> _Halls;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnrIdChanging(int value);
    partial void OnrIdChanged();
    partial void OnrSeatChanging(int value);
    partial void OnrSeatChanged();
    partial void OnmIdChanging(int value);
    partial void OnmIdChanged();
    partial void OnhIdChanging(int value);
    partial void OnhIdChanged();
    #endregion
		
		public Reservation()
		{
			this._Movies = new EntitySet<Movie>(new Action<Movie>(this.attach_Movies), new Action<Movie>(this.detach_Movies));
			this._Halls = new EntitySet<Hall>(new Action<Hall>(this.attach_Halls), new Action<Hall>(this.detach_Halls));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int rId
		{
			get
			{
				return this._rId;
			}
			set
			{
				if ((this._rId != value))
				{
					this.OnrIdChanging(value);
					this.SendPropertyChanging();
					this._rId = value;
					this.SendPropertyChanged("rId");
					this.OnrIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rSeat", DbType="Int NOT NULL")]
		public int rSeat
		{
			get
			{
				return this._rSeat;
			}
			set
			{
				if ((this._rSeat != value))
				{
					this.OnrSeatChanging(value);
					this.SendPropertyChanging();
					this._rSeat = value;
					this.SendPropertyChanged("rSeat");
					this.OnrSeatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mId", DbType="Int NOT NULL")]
		public int mId
		{
			get
			{
				return this._mId;
			}
			set
			{
				if ((this._mId != value))
				{
					this.OnmIdChanging(value);
					this.SendPropertyChanging();
					this._mId = value;
					this.SendPropertyChanged("mId");
					this.OnmIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hId", DbType="Int NOT NULL")]
		public int hId
		{
			get
			{
				return this._hId;
			}
			set
			{
				if ((this._hId != value))
				{
					this.OnhIdChanging(value);
					this.SendPropertyChanging();
					this._hId = value;
					this.SendPropertyChanged("hId");
					this.OnhIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Reservation_Movie", Storage="_Movies", ThisKey="mId", OtherKey="mId")]
		public EntitySet<Movie> Movies
		{
			get
			{
				return this._Movies;
			}
			set
			{
				this._Movies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Reservation_Hall", Storage="_Halls", ThisKey="hId", OtherKey="hId")]
		public EntitySet<Hall> Halls
		{
			get
			{
				return this._Halls;
			}
			set
			{
				this._Halls.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Movies(Movie entity)
		{
			this.SendPropertyChanging();
			entity.Reservation = this;
		}
		
		private void detach_Movies(Movie entity)
		{
			this.SendPropertyChanging();
			entity.Reservation = null;
		}
		
		private void attach_Halls(Hall entity)
		{
			this.SendPropertyChanging();
			entity.Reservation = this;
		}
		
		private void detach_Halls(Hall entity)
		{
			this.SendPropertyChanging();
			entity.Reservation = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Movie")]
	public partial class Movie : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mId;
		
		private string _mTitle;
		
		private string _mDescription;
		
		private string _mPictureUrl;
		
		private string _mVideoUrl;
		
		private EntityRef<Reservation> _Reservation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmIdChanging(int value);
    partial void OnmIdChanged();
    partial void OnmTitleChanging(string value);
    partial void OnmTitleChanged();
    partial void OnmDescriptionChanging(string value);
    partial void OnmDescriptionChanged();
    partial void OnmPictureUrlChanging(string value);
    partial void OnmPictureUrlChanged();
    partial void OnmVideoUrlChanging(string value);
    partial void OnmVideoUrlChanged();
    #endregion
		
		public Movie()
		{
			this._Reservation = default(EntityRef<Reservation>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int mId
		{
			get
			{
				return this._mId;
			}
			set
			{
				if ((this._mId != value))
				{
					if (this._Reservation.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmIdChanging(value);
					this.SendPropertyChanging();
					this._mId = value;
					this.SendPropertyChanged("mId");
					this.OnmIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mTitle", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string mTitle
		{
			get
			{
				return this._mTitle;
			}
			set
			{
				if ((this._mTitle != value))
				{
					this.OnmTitleChanging(value);
					this.SendPropertyChanging();
					this._mTitle = value;
					this.SendPropertyChanged("mTitle");
					this.OnmTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mDescription", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string mDescription
		{
			get
			{
				return this._mDescription;
			}
			set
			{
				if ((this._mDescription != value))
				{
					this.OnmDescriptionChanging(value);
					this.SendPropertyChanging();
					this._mDescription = value;
					this.SendPropertyChanged("mDescription");
					this.OnmDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mPictureUrl", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string mPictureUrl
		{
			get
			{
				return this._mPictureUrl;
			}
			set
			{
				if ((this._mPictureUrl != value))
				{
					this.OnmPictureUrlChanging(value);
					this.SendPropertyChanging();
					this._mPictureUrl = value;
					this.SendPropertyChanged("mPictureUrl");
					this.OnmPictureUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mVideoUrl", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string mVideoUrl
		{
			get
			{
				return this._mVideoUrl;
			}
			set
			{
				if ((this._mVideoUrl != value))
				{
					this.OnmVideoUrlChanging(value);
					this.SendPropertyChanging();
					this._mVideoUrl = value;
					this.SendPropertyChanged("mVideoUrl");
					this.OnmVideoUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Reservation_Movie", Storage="_Reservation", ThisKey="mId", OtherKey="mId", IsForeignKey=true)]
		public Reservation Reservation
		{
			get
			{
				return this._Reservation.Entity;
			}
			set
			{
				Reservation previousValue = this._Reservation.Entity;
				if (((previousValue != value) 
							|| (this._Reservation.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Reservation.Entity = null;
						previousValue.Movies.Remove(this);
					}
					this._Reservation.Entity = value;
					if ((value != null))
					{
						value.Movies.Add(this);
						this._mId = value.mId;
					}
					else
					{
						this._mId = default(int);
					}
					this.SendPropertyChanged("Reservation");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
